name: resourcegroup_deployment
on: 
    push
env:
   ARM_TEMPLATE: infra/rsd.json
   name: lol
   SUBSCRIPTION_ID: ${{ secrets.SUBSCRIBE_ID}}

jobs:
    deployment:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: azure login
          uses: azure/login@v2
          with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: azure set subscription
          run: |
            az account set --subscription ${{secrets.SUBSCRIPTION}}
    
        - name: deployment
          run: |
            az deployment group  --template-file ${{env.ARM_TEMPLATE}}


