name: resourcegroup_deployment
on: 
    push
env:
   ARM_TEMPLATE: infra/rsd.json
   name: lol
   SUBSCRIPTION_ID: ${{ secrets.SUBSCRIBE_ID}}
   location: uksouth
   resource-group: prueba_cicd 

jobs:
    deployment:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        # - name: azure login
        #   uses: azure/login@v2
        #   with:
        #    creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        # - name: azure set subscription
        #   run: |
        #     az account set --subscription ${{secrets.SUBSCRIPTION}}
    
        # - name: azure rs creation
        #   run: |
        #     az group create --name ${{env.resource-group}} --location ${{env.location}}
        # - name: deployment
        #   run: |
        #     az deployment group  create  --resource-group ${{env.resource-group}}  --template-file ${{env.ARM_TEMPLATE}}


        - name: v1
          run: |
            export Chorradas=3342
        

        - name: v2
          run: |
            ls -lha   
        - name: v3
          run: |
            echo "kkk $Chorradas"
            
        - name: Set another variable
          id: set_my_var
          run: echo "::set-output name=my_var::new_value"

        - name: Use the variable
          run: echo "${{ steps.set_my_var.outputs.my_var }}" 